version: '3'

services:
  avarts:
    image: avarts:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - data:/app/db/pb_data

volumes:
  data:
